# action.yml
name: 'xHello World'
description: 'Greet someone and record the time'
inputs:
  processId:  # id of input
    description: 'processId!'
    required: true
    default: 'Me'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.processId }}
