name: createPackage
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.gitignore'
      - '.github/workflows/**'
jobs:
  crPackage:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
    - name: List changed files
      id: get_changed_files             
      env:
        authToken: ${{ secrets.BOOMI }}
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
           compId=$(grep '^componentId=' $file | cut -f2 -d'=')
           compVer=$(grep '^ver=' $file | cut -f2 -d'=')
           compNotes=$(grep '^notes=' $file | cut -f2 -d'=')
           
           chmod +x /home/peter/src/PAC/initcrPackage.sh
           /home/peter/src/PAC/initcrPackage.sh authToken=${{ secrets.BOOMI }} componentId=$compId packageVersion=$compVer notes="$compNotes"
        done
    - uses: actions/checkout@v3
