name: createPackage
on: push
jobs:
  crPackage:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Get name of changed file
      run: echo "file: ${github.event.head_commit.modified[0]}"
    - name: Run script file
      env:
        authToken: ${{ secrets.BOOMI }}
      run: |
         content=`cat procGeneral`
         echo $GITHUB_EVENT_NAME
         #echo ${{ secrets.BOOMI }}
         #echo "::set-output name=componentId::$content"
         chmod +x /home/peter/src/PAC/initcrPackage.sh
         /home/peter/src/PAC/initcrPackage.sh authToken=${{ secrets.BOOMI }} componentId=111 packageVersion=222 notes="test notes"
      shell: bash
