name: createPackage
on: push
jobs:
  crPackage:
    runs-on: self-hosted
    steps:
    - name: Set environment variable
        env:
          MY_VARIABLE: ${{ steps.read_file.outputs.file_content }}
        run: echo $MY_VARIABLE
      - name: Read file
        id: read_file
        run: echo "::set-output name=file_content::$(cat procGeneral)"
    #- name: Get name of changed file
    #  run: echo ${{ github.event.head_commit.modified }}
    - uses: actions/checkout@v3
    - name: Run script file
      env:
        authToken: ${{ secrets.BOOMI }}
      run: |
         content=`cat procGeneral`
         echo $GITHUB_EVENT_NAME
         #echo ${{ secrets.BOOMI }}
         #echo "::set-output name=componentId::$content"
         chmod +x /home/peter/src/PAC/initcrPackage.sh
         /home/peter/src/PAC/initcrPackage.sh authToken=${{ secrets.BOOMI }} componentId=111 packageVersion=222 notes="test notes"
      shell: bash
