name: createPackage
on: push
jobs:
  crPackage:
    runs-on: self-hosted
    steps:
    - name: Read file
      id: read_file
      run: |
        echo "::set-output name=inComponentId::$(grep '^componentId=' procGeneral)"
        echo "::set-output name=inVer::$(grep '^ver=' procGeneral)"
        echo "::set-output name=inNotes::$(grep '^notes=' procGeneral)"
    - uses: actions/checkout@v3
    - name: Run script file
      env:
        authToken: ${{ secrets.BOOMI }}
        componentId: ${{ steps.read_file.outputs.inComponentId }}
        ver: ${{ steps.read_file.outputs.inVer }}
        notes: ${{ steps.read_file.outputs.inNotes }}
      run: |
        chmod +x /home/peter/src/PAC/initcrPackage.sh
        /home/peter/src/PAC/initcrPackage.sh authToken=${{ secrets.BOOMI }} componentId=${{ env.componentId }} packageVersion=${{ env.ver }} notes="${{ env.notes }}"
      shell: bash
