name: createPackage
on: push
jobs:
  crPackage:
    runs-on: self-hosted
    steps:
    - name: Read file
      id: read_file
      run:
        echo "::set-output name=inComponentId::$(grep componentId= procGeneral)"
    - name: Set environment variable
      env:
        componentId: ${{ steps.read_file.outputs.inComponentId }}
      run:
        echo $inComponentId
    - uses: actions/checkout@v3
    - name: Run script file
      env:
        authToken: ${{ secrets.BOOMI }}
      run: |
         chmod +x /home/peter/src/PAC/initcrPackage.sh
         #/home/peter/src/PAC/initcrPackage.sh authToken=${{ secrets.BOOMI }} componentId=${{ componentId }} packageVersion=${{ ver }} notes="${{ notes }}"
      shell: bash

