name: createPackage
on: push
jobs:
  crPackage:
    runs-on: self-hosted
    steps:
    - name: Read file
      id: read_file
      run:
        echo "::set-output name=inComponentId::$(grep componentId= procGeneral)"
        #echo "::set-output name=inVer::$(grep ver= procGeneral)"
        #echo "::set-output name=inNotes::$(grep notes= procGeneral)"
    - name: Set environment variable
      env:
        componentId: ${{ steps.read_file.outputs.inComponentId }}
        #ver: ${{ steps.read_file.outputs.inVer }}
        #notes: ${{ steps.read_file.outputs.inNotes }}
      #run:
        #echo $componentId
        #echo $notes
    #- name: Get name of changed file
    #  run: echo ${{ github.event.head_commit.modified }}
    - uses: actions/checkout@v3
    - name: Run script file
      env:
        authToken: ${{ secrets.BOOMI }}
      run: |
         #content=`cat procGeneral`
         #echo $GITHUB_EVENT_NAME
         #echo ${{ secrets.BOOMI }}
         #echo "::set-output name=componentId::$content"
         chmod +x /home/peter/src/PAC/initcrPackage.sh
         #/home/peter/src/PAC/initcrPackage.sh authToken=${{ secrets.BOOMI }} componentId=${{ componentId }} packageVersion=${{ ver }} notes="${{ notes }}"
      shell: bash

