name: createPackage
on: push
jobs:
  crPackage:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Run script file
      #env:
           #componentId: 11121
      run: |
         content=`cat procGeneral`
         echo ${{ secrets.BOOMI }}
         #echo "::set-output name=componentId::$content"
         chmod +x /home/peter/src/PAC/initcrPackage.sh
         /home/peter/src/PAC/initcrPackage.sh ${{ secrets.BOOMI }} 111 222 "test notes"
      shell: bash
