name: deployPackage
on:
  push:
    branches:
      - dev
    paths-ignore:
      - '.gitignore'
      - '.github/workflows/**'
jobs:
  deployPackage:
    runs-on: ubuntu-latest
    steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
    - name: List changed files
      id: get_changed_files             
      env:
        authToken: ${{ secrets.BOOMI }}
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
           componentId=$(grep '^componentId=' $file | cut -f2 -d'=')
           #packageId=$(grep '^packageId=' $file | cut -f2 -d'=')
           compVer=$(grep '^ver=' $file | cut -f2 -d'=')
           targetEnv=$(grep '^targetEnv=' $file | cut -f2 -d'=')
           listenerStatus=$(grep '^listenerStatus=' $file | cut -f2 -d'=')
           notes=$(grep '^notes=' $file | cut -f2 -d'=')
           
           chmod +x /home/peter/src/PAC/initdeployPackage.sh
           /home/peter/src/PAC/initdeployPackage.sh authToken=${{ secrets.BOOMI }} componentId=$componentId env=$targetEnv packageVersion=$compVer notes="$notes" listenerStatus=$listenerStatus
        done
    - uses: actions/checkout@v3
