name: deployPackage
on: push
jobs:
  deployPackage:
    runs-on: self-hosted
    steps:
    - name: Read file
      id: read_file
      run: |
        echo "::set-output name=inComponentId::$(grep '^componentId=' procGeneral | cut -f2 -d'=')"
        echo "::set-output name=inPackageId::$(grep '^packageId=' procGeneral | cut -f2 -d'=')"
        echo "::set-output name=inVer::$(grep '^ver=' procGeneral | cut -f2 -d'=')"
        echo "::set-output name=inTargetEnv::$(grep '^targetEnv=' procGeneral | cut -f2 -d'=')"
        echo "::set-output name=inlistenerStatus::$(grep '^listenerStatus=' procGeneral | cut -f2 -d'=')"
        echo "::set-output name=inNotes::$(grep '^notes=' procGeneral | cut -f2 -d'=')"
    - uses: actions/checkout@v3
    - name: Run script file
      env:
        authToken: ${{ secrets.BOOMI }}
        componentId: ${{ steps.read_file.outputs.inComponentId }}
        packageId: ${{ steps.read_file.outputs.inPackageId }}
        ver: ${{ steps.read_file.outputs.inVer }}
        targetEnv: ${{ steps.read_file.outputs.inTargetEnv }}
        listenerStatus: ${{ steps.read_file.outputs.inListenerStatus }}
        notes: ${{ steps.read_file.outputs.inNotes }}
      run: |
        chmod +x /home/peter/src/PAC/initdeployPackage.sh
        /home/peter/src/PAC/initdeployPackage.sh authToken=${{ secrets.BOOMI }} componentId=${{ env.componentId }} env=$targetEnv packageVersion=$ver notes="$notes" listenerStatus=$listenerStatus
      shell: bash
      

